### ISSUE TITLE
Invalid int64 decoding of negative values

### ISSUE THREAD

**Issue by gmartsenkov** [jeromegn/protobuf.cr#44]
Encoding negative i64 produces a wrong number, this might as well be the case for i32;
 
```crystal
  it "V3 int64 encode decode" do
    msg = TestMessagesV3::Test3.new
    msg.f2=-15000_i64

    some_io = IO::Memory.new
    msg.to_protobuf some_io

    some_io.rewind

    msg2 = TestMessagesV3::Test3.from_protobuf some_io
    msg2.f2.should eq -15000_i64
  end
```

Fails with:
```
Failures:

  1) Protobuf::Message V3 int64 encode decode
     Failure/Error: msg2.f2.should eq -15000_i64

       Expected: -15000
            got: 9223372036854760808

     # spec/protobuf/decode_spec.cr:31
```
